# -*- coding: utf-8 -*-
"""Praktisi 1 Pradytha Galuh Putranti 013

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uOFgreen77lmaojOkQsLPGLQro6o5aus

# **TUGAS 1 PRAKTISI PMML**

# Books to Scrape - Web Scraper & Data Analysis

# Scraping program untuk website "https://books.toscrape.com/

# **Pradytha Galuh Putranti**

**Statistika dan Sains Data**

**2304220013**
"""

pip install requests beautifulsoup4

import requests
from bs4 import BeautifulSoup
import csv
import re
from urllib.parse import urljoin

def get_rating_number(rating_class):
    """Convert rating class to number"""
    ratings = {
        'One': 1,
        'Two': 2,
        'Three': 3,
        'Four': 4,
        'Five': 5
    }
    for key in ratings:
        if key in rating_class:
            return ratings[key]
    return 0

def scrape_book_details(book_url, base_url):
    """Scrape detailed information from individual book page"""
    try:
        response = requests.get(book_url)
        response.raise_for_status()
        soup = BeautifulSoup(response.content, 'html.parser')

        # Get product information table
        table = soup.find('table', class_='table table-striped')
        product_info = {}

        if table:
            rows = table.find_all('tr')
            for row in rows:
                header = row.find('th').text.strip()
                value = row.find('td').text.strip()
                product_info[header] = value

        # Get description
        description = ''
        product_desc = soup.find('div', id='product_description')
        if product_desc:
            desc_p = product_desc.find_next_sibling('p')
            if desc_p:
                description = desc_p.text.strip()

        # Get number of reviews
        num_reviews = product_info.get('Number of reviews', '0')

        # Get stock status and number
        availability = product_info.get('Availability', '')
        stock_status = 'Out of stock'
        stock_number = 0

        if availability:
            if 'In stock' in availability:
                stock_status = 'In stock'
                # Extract number from "In stock (22 available)"
                match = re.search(r'\((\d+) available\)', availability)
                if match:
                    stock_number = int(match.group(1))

        return {
            'price_excl_tax': product_info.get('Price (excl. tax)', ''),
            'price_incl_tax': product_info.get('Price (incl. tax)', ''),
            'tax': product_info.get('Tax', ''),
            'stock_status': stock_status,
            'stock_number': stock_number,
            'description': description,
            'num_reviews': num_reviews
        }
    except Exception as e:
        print(f"Error scraping book details from {book_url}: {e}")
        return None

def scrape_books(base_url='https://books.toscrape.com/'):
    """Main function to scrape all books from the website"""
    all_books = []
    page = 1

    print("Starting scraping process...")

    while True:
        # Construct URL for current page
        if page == 1:
            url = base_url + 'catalogue/page-1.html'
        else:
            url = f"{base_url}catalogue/page-{page}.html"

        print(f"Scraping page {page}...")

        try:
            response = requests.get(url)
            response.raise_for_status()
        except requests.exceptions.HTTPError:
            print(f"No more pages found. Total pages scraped: {page - 1}")
            break

        soup = BeautifulSoup(response.content, 'html.parser')
        books = soup.find_all('article', class_='product_pod')

        if not books:
            break

        for book in books:
            # Get basic info from listing page
            title_tag = book.find('h3').find('a')
            title = title_tag['title']
            book_path = title_tag['href']
            book_url = urljoin(base_url + 'catalogue/', book_path)

            # Get image URL
            img_tag = book.find('img')
            img_url = urljoin(base_url, img_tag['src']) if img_tag else ''

            # Get rating
            rating_tag = book.find('p', class_='star-rating')
            rating = get_rating_number(rating_tag['class']) if rating_tag else 0

            # Get price from listing page
            price_tag = book.find('p', class_='price_color')
            price = price_tag.text.strip() if price_tag else ''

            # Get category (from breadcrumb on detail page will be more accurate)
            # For now, we'll get it from the detail page

            print(f"  - Scraping: {title}")

            # Get detailed information
            details = scrape_book_details(book_url, base_url)

            if details:
                # Get category from detail page
                detail_response = requests.get(book_url)
                detail_soup = BeautifulSoup(detail_response.content, 'html.parser')
                breadcrumb = detail_soup.find('ul', class_='breadcrumb')
                category = ''
                if breadcrumb:
                    category_link = breadcrumb.find_all('a')
                    if len(category_link) >= 3:
                        category = category_link[2].text.strip()

                book_data = {
                    'category': category,
                    'code': book_url.split('/')[-2],  # Extract code from URL
                    'cover_url': img_url,
                    'title': title,
                    'rating': rating,
                    'price_excl_tax': details['price_excl_tax'],
                    'price_incl_tax': details['price_incl_tax'],
                    'tax': details['tax'],
                    'stock_status': details['stock_status'],
                    'stock_number': details['stock_number'],
                    'description': details['description'],
                    'num_reviews': details['num_reviews']
                }

                all_books.append(book_data)

        page += 1

    return all_books

def save_to_csv(books, filename='books_data.csv'):
    """Save scraped data to CSV file"""
    if not books:
        print("No data to save!")
        return

    fieldnames = [
        'category', 'code', 'cover_url', 'title', 'rating',
        'price_excl_tax', 'price_incl_tax', 'tax',
        'stock_status', 'stock_number', 'description', 'num_reviews'
    ]

    with open(filename, 'w', newline='', encoding='utf-8') as csvfile:
        writer = csv.DictWriter(csvfile, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(books)

    print(f"\nData saved to {filename}")
    print(f"Total books scraped: {len(books)}")

if __name__ == "__main__":
    # Scrape all books
    books = scrape_books()

    # Save to CSV
    save_to_csv(books)

    # Display sample data
    if books:
        print("\n=== Sample Data (First Book) ===")
        first_book = books[0]
        for key, value in first_book.items():
            print(f"{key}: {value}")

import pandas as pd

# Baca CSV
df = pd.read_csv('books_data.csv')

# Lihat 10 data pertama
print(df.head(10))

# Info dataset
print(f"\nTotal buku: {len(df)}")
print(f"\nKolom yang ada: {df.columns.tolist()}")

"""# **Analisis sederhana**"""

# Buku dengan rating tertinggi
print("=== Top 10 Buku Rating Tertinggi ===")
print(df.nlargest(10, 'rating')[['title', 'rating', 'price_incl_tax']])

# Buku termurah dan termahal
print(f"\nBuku termurah: {df['price_incl_tax'].min()}")
print(f"Buku termahal: {df['price_incl_tax'].max()}")

# Kategori terbanyak
print("\n=== Jumlah Buku per Kategori ===")
print(df['category'].value_counts())